# Generated by Django 5.1.6 on 2025-02-14 09:09

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=500)),
                ('contact_phone', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_company_name', models.CharField(max_length=500)),
                ('contact_company_desc', models.TextField(default='')),
                ('contact_company_logo', cloudinary.models.CloudinaryField(default='', max_length=255)),
                ('contact_company_link', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Enter ATM Supplier Info',
                'verbose_name_plural': 'Enter ATM Supplier Info',
            },
        ),
        migrations.CreateModel(
            name='ATSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
                ('category_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('category_text', models.TextField(blank=True, null=True)),
                ('product_category', models.CharField(blank=True, choices=[('Agri Clinic', 'Agri Clinic'), ('Agritech', 'Agritech')], max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Global Agritech & ATM: Enter Category Info',
                'verbose_name_plural': 'Global Agritech & ATM: Enter Category Info',
            },
        ),
        migrations.CreateModel(
            name='ATSIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Enter ATM Introduction',
                'verbose_name_plural': 'Enter ATM Introduction',
            },
        ),
        migrations.CreateModel(
            name='ATSSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=500)),
                ('seller_company', models.CharField(max_length=500)),
                ('seller_address', models.TextField()),
                ('seller_email_id', models.EmailField(max_length=254)),
                ('seller_product_avail', models.BooleanField(default=False)),
                ('seller_plan', models.TextField()),
            ],
            options={
                'verbose_name': 'Get ATM Seller Enquiry & Feedback',
                'verbose_name_plural': 'Get ATM Seller Enquiry & Feedback',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(default='', max_length=500)),
                ('link', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Upload Banner Images',
                'verbose_name_plural': 'Upload Banner Images',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('blog_heading', models.CharField(default='', max_length=255)),
                ('blog_description', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('embed_url', models.TextField(default='')),
                ('video_heading', models.CharField(default='', max_length=255)),
                ('video_description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Post Blogs',
                'verbose_name_plural': 'Post Blogs',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Home & About Us: Upload Collaboration Images',
                'verbose_name_plural': 'Home & About Us: Upload Collaboration Images',
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('Time', models.DateTimeField(null=True)),
                ('is_seen', models.BooleanField(null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('stateDistrict', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Number',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10, null=True)),
                ('place', models.CharField(default='', max_length=500)),
                ('comments', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_seen', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Get User Messages',
                'verbose_name_plural': 'Get User Messages',
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('type_of_image', models.CharField(choices=[('awards', 'Awards'), ('media coverages', 'Media Coverages'), ('approvals and licenses', 'Approvals and Licenses')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Upload Credential Images',
                'verbose_name_plural': 'Upload Credential Images',
            },
        ),
        migrations.CreateModel(
            name='DripIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, max_length=1000, null=True)),
                ('text4', models.CharField(blank=True, max_length=1000, null=True)),
                ('text5', models.CharField(blank=True, max_length=1000, null=True)),
                ('text6', models.CharField(blank=True, max_length=1000, null=True)),
                ('text7', models.CharField(blank=True, max_length=1000, null=True)),
                ('text8', models.CharField(blank=True, max_length=1000, null=True)),
                ('text9', models.CharField(blank=True, max_length=1000, null=True)),
                ('text10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_img', cloudinary.models.CloudinaryField(max_length=255)),
                ('featured_alt', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Upload Featured Listing Images',
                'verbose_name_plural': 'Upload Featured Listing Images',
            },
        ),
        migrations.CreateModel(
            name='GlobalAgritechProductAvgRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500)),
                ('avg_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(default='', max_length=500)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Enter Cross Promotion Content',
                'verbose_name_plural': 'Enter Cross Promotion Content',
            },
        ),
        migrations.CreateModel(
            name='Home_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageone', cloudinary.models.CloudinaryField(max_length=255)),
                ('imagetwo', cloudinary.models.CloudinaryField(max_length=255)),
                ('imagethree', cloudinary.models.CloudinaryField(max_length=255)),
                ('hedding', models.CharField(max_length=255)),
                ('information', models.TextField()),
                ('Kannada_text', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Enter Website Introduction',
                'verbose_name_plural': 'Enter Website Introduction',
            },
        ),
        migrations.CreateModel(
            name='HondaSpares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, max_length=1000, null=True)),
                ('text4', models.CharField(blank=True, max_length=1000, null=True)),
                ('text5', models.CharField(blank=True, max_length=1000, null=True)),
                ('text6', models.CharField(blank=True, max_length=1000, null=True)),
                ('text7', models.CharField(blank=True, max_length=1000, null=True)),
                ('text8', models.CharField(blank=True, max_length=1000, null=True)),
                ('text9', models.CharField(blank=True, max_length=1000, null=True)),
                ('text10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntechCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('country_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Enter Global Agritech Country Data',
                'verbose_name_plural': 'Enter Global Agritech Country Data',
            },
        ),
        migrations.CreateModel(
            name='IntechFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=500)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_rating', models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')])),
                ('user_feedback', models.TextField()),
            ],
            options={
                'verbose_name': 'Get Global Agritech Product Feedback',
                'verbose_name_plural': 'Get Global Agritech Product Feedback',
            },
        ),
        migrations.CreateModel(
            name='IntechIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('intro_text', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Enter Global Agritech Introduction',
                'verbose_name_plural': 'Enter Global Agritech Introduction',
            },
        ),
        migrations.CreateModel(
            name='IntechRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_title', models.CharField(max_length=500)),
                ('ppt', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Global Agritech & ATM: Enter Roadmap Details',
                'verbose_name_plural': 'Global Agritech & ATM: Enter Roadmap Details',
            },
        ),
        migrations.CreateModel(
            name='IntechSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=500)),
                ('seller_company', models.CharField(max_length=500)),
                ('seller_address', models.TextField()),
                ('seller_email_id', models.EmailField(max_length=254)),
                ('seller_product_avail_india', models.BooleanField()),
                ('seller_plan', models.TextField()),
                ('seller_feedback', models.TextField()),
            ],
            options={
                'verbose_name': 'Get Global Agritech Seller Enquiry & Feedback',
                'verbose_name_plural': 'Get Global Agritech Seller Enquiry & Feedback',
            },
        ),
        migrations.CreateModel(
            name='KCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, max_length=1000, null=True)),
                ('text4', models.CharField(blank=True, max_length=1000, null=True)),
                ('text5', models.CharField(blank=True, max_length=1000, null=True)),
                ('text6', models.CharField(blank=True, max_length=1000, null=True)),
                ('text7', models.CharField(blank=True, max_length=1000, null=True)),
                ('text8', models.CharField(blank=True, max_length=1000, null=True)),
                ('text9', models.CharField(blank=True, max_length=1000, null=True)),
                ('text10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Enter K Center Data',
                'verbose_name_plural': 'Enter K Center Data',
            },
        ),
        migrations.CreateModel(
            name='kcentertopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktopic', models.CharField(max_length=200)),
                ('ktopic_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('ktopicimg', cloudinary.models.CloudinaryField(max_length=255)),
                ('ktopicintro', models.TextField(default='')),
                ('text1', models.CharField(blank=True, max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, max_length=1000, null=True)),
                ('text4', models.CharField(blank=True, max_length=1000, null=True)),
                ('text5', models.CharField(blank=True, max_length=1000, null=True)),
                ('text6', models.CharField(blank=True, max_length=1000, null=True)),
                ('text7', models.CharField(blank=True, max_length=1000, null=True)),
                ('text8', models.CharField(blank=True, max_length=1000, null=True)),
                ('ktopicconclusion', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Enter KCenter Category-Specific Topic',
                'verbose_name_plural': 'Enter KCenter Category-Specific Topic',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Upload Website Logo',
                'verbose_name_plural': 'Upload Website Logo',
            },
        ),
        migrations.CreateModel(
            name='Numberofvisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, null=True)),
                ('district', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Number of visits',
                'verbose_name_plural': 'Number of visits',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Farm Machinaries', 'Farm Machinaries'), ('Implements & Others', 'Implements & Others'), ('Irrigation Systems', 'Irrigation Systems')], max_length=200, null=True)),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('backlinks', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('pinfo', models.TextField(blank=True)),
                ('Highlight_image1', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('Highlight_image2', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('text2', models.CharField(blank=True, max_length=255)),
                ('Highlight_image3', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('text3', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('background_gif', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('exclusive_img', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('exclusive_img_alt', models.CharField(blank=True, max_length=500, null=True)),
                ('exclusive_highlight_text', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Enter Product Categories Data',
                'verbose_name_plural': 'Enter Product Categories Data',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('whatsapp_no', models.CharField(default='', max_length=10)),
                ('rating', models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')])),
                ('review', models.TextField(blank=True, null=True)),
                ('r_image', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255)),
                ('product', models.CharField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('review_token', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('ip_address', models.CharField(default='', max_length=500)),
                ('is_important', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Get User's Product Reviews",
                'verbose_name_plural': "Get User's Product Reviews",
            },
        ),
        migrations.CreateModel(
            name='SeoPageExtLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('video blogs', 'Video Blogs'), ('gloabl-agritech', 'Global Agritech'), ('kcenter', 'K Center'), ('agritech-mart', 'Agritech Mart')], max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('backlinks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enter SEO Content Page Wise',
                'verbose_name_plural': 'Enter SEO Content Page Wise',
            },
        ),
        migrations.CreateModel(
            name='ATSContactProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.atscontactinfo')),
            ],
            options={
                'verbose_name': 'Enter ATM Supplier Product Info',
                'verbose_name_plural': 'Enter ATM Supplier Product Info',
            },
        ),
        migrations.CreateModel(
            name='ATSContactProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', cloudinary.models.CloudinaryField(default='', max_length=255)),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appagri.atscontactinfo')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.atscontactproductinfo')),
            ],
            options={
                'verbose_name': 'Enter ATM Supplier Product images',
                'verbose_name_plural': 'Enter ATM Supplier Product images',
            },
        ),
        migrations.AddField(
            model_name='atscontactinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.atsinfo'),
        ),
        migrations.CreateModel(
            name='ATSSellerProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_product_images', cloudinary.models.CloudinaryField(max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.atsseller')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appagri.blogs')),
            ],
            options={
                'verbose_name': 'Get Blogs Comments',
                'verbose_name_plural': 'Get Blogs Comments',
            },
        ),
        migrations.CreateModel(
            name='IntechCategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=500)),
                ('category_intro', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.intechcountry')),
            ],
            options={
                'verbose_name': 'Enter Global Agritech Category',
                'verbose_name_plural': 'Enter Global Agritech Category',
            },
        ),
        migrations.CreateModel(
            name='IntechProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_class', models.CharField(blank=True, max_length=500, null=True)),
                ('seller_name', models.CharField(max_length=500)),
                ('seller_details', models.TextField(blank=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('product_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.intechcategorydetails')),
            ],
            options={
                'verbose_name': 'Enter Global Agritech Product',
                'verbose_name_plural': 'Enter Global Agritech Product',
            },
        ),
        migrations.CreateModel(
            name='IntechSellerProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_product_images', cloudinary.models.CloudinaryField(max_length=255)),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appagri.intechseller')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.review')),
            ],
            options={
                'verbose_name': "Admin Response to User's Reviews",
                'verbose_name_plural': "Admin Response to User's Reviews",
            },
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('spimage', cloudinary.models.CloudinaryField(max_length=255)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spinfo', models.TextField()),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('rateing', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('Key_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_2', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_2', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_3', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_3', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_4', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_4', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_5', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_5', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_6', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_6', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_7', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_7', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_8', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_8', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_9', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_9', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_10', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_10', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_11', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_11', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_12', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_12', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_13', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_13', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_14', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_14', models.CharField(blank=True, max_length=255, null=True)),
                ('Key_15', models.CharField(blank=True, max_length=255, null=True)),
                ('Value_15', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appagri.product')),
            ],
            options={
                'verbose_name': 'Enter Products Data',
                'verbose_name_plural': 'Enter Products Data',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Subproduct_External_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_desc', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('external_links', models.TextField(blank=True, null=True)),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct_external_links', to='appagri.subproduct')),
            ],
            options={
                'verbose_name': 'Enter Products SEO Contents',
                'verbose_name_plural': 'Enter Products SEO Contents',
            },
        ),
    ]
