# Generated by Django 5.1.6 on 2025-02-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
