# Generated by Django 5.1.5 on 2025-02-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagri', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intechproduct',
            name='product_class',
            field=models.CharField(blank=True, choices=[('seeds_plants', 'Seeds & Plants'), ('irrigation_fertilizers', 'Irrigation & Fertilizers'), ('fertilizers_organic_bio_products', 'Fertilizers - Organic & Bio Products'), ('fertilizers_inorganic', 'Fertilizers - Inorganic'), ('pesticide_organic_inorganic', 'Pesticide Organic and Inorganic'), ('farm_machinery_agri_services', 'Farm Machinery and Agri Services')], max_length=500, null=True),
        ),
    ]
